{% set version = "6.6.1" %}

package:
  name: robotframework-seleniumlibrary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-seleniumlibrary/robotframework_seleniumlibrary-{{ version }}.tar.gz
  sha256: 6fd3a20c0ca70425d2c4b89e372d2c2399aa059a815c8cab87a2616bcfece7b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .
  entry_points:
    - selib=SeleniumLibrary.entry.__main__:cli

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - click >=8.1.7
    - python >=3.8
    - robotframework >=4.1.3
    - robotframework-pythonlibcore >=4.4.1
    - selenium >=4.3.0

test:
  requires:
    - pip
  imports:
    - SeleniumLibrary
  commands:
    - python -m pip check
    - selib --version
    - selib --help

about:
  home: https://github.com/robotframework/SeleniumLibrary
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  summary: Web testing library for Robot Framework
  doc_url: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
  description: |
    SeleniumLibrary is a web testing library for Robot Framework that utilizes
    the Selenium tool internally. The project is hosted on GitHub and downloads
    can be found from PyPI.

    SeleniumLibrary works with Selenium 3 and 4. It supports Python 3.6 or newer.
    In addition to the normal Python interpreter, it works also with PyPy.

extra:
  recipe-maintainers:
    - bollwyvl
