{% set name = "robotframework-seleniumlibrary" %}
{% set version = "6.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64686f6aa98b1fd1c340715c0adf8c09b6b405564086fbe672de31498a26ff0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - robotframework >=3.2.2
    - robotframework-pythonlibcore >=2.2.1
    - selenium >=4.0.0

test:
  requires:
    - pip
  imports:
    - SeleniumLibrary
  commands:
    - python -m pip check

about:
  home: https://github.com/robotframework/SeleniumLibrary
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  summary: Web testing library for Robot Framework
  doc_url: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
  dev_url: https://github.com/robotframework/SeleniumLibrary
  description: |
    SeleniumLibrary is a web testing library for Robot Framework that utilizes 
    the Selenium tool internally. The project is hosted on GitHub and downloads 
    can be found from PyPI.

    SeleniumLibrary works with Selenium 3 and 4. It supports Python 3.6 or newer. 
    In addition to the normal Python interpreter, it works also with PyPy.

extra:
  recipe-maintainers:
    - bollwyvl
